### ISSUE TITLE
How to specify the folder for BioNLPST training model

### ISSUE THREAD

**Issue by JingboXia** [jakelever/kindred#1]
When I try 
>>>trainCorpus = kindred.bionlpst.load('2016-BB3-event-train')
It reports:
RuntimeError: Unable to download BioNLP ST files

I downloaded the model from http://2016.bionlp-st.org/tasks/bb2/BioNLP-ST-2016_BB-event_train.zip, then.
Where can I put the model file and avoid repeatedly downloading?

Thanks.

**Comment by jakelever** [comment]
Hey, thanks for creating an issue for this. Firstly, I'd like to figure out the error, and below is a workaround for just loading the downloaded files. Can you tell me what platform (Linux distro/MacOs?) you are using and what version of Python?

Kindred normally downloads the model files into a temporary directory and cleans up afterwards. Keeping the files is a planned improvement that I will hopefully add pretty quickly.

Kindred simply downloads the files, unzips it and then uses the command below and replace DIRECTORY with the file locations. 

```
corpus = kindred.loadDir(dataFormat='standoff',directory=DIRECTORY)
```

You can check what has been loaded and get counts of different things with this code:

```
fileCount = len(corpus.documents)
entityCount = sum([ len(d.getEntities()) for d in corpus.documents ])
relationCount = sum([ len(d.getRelations()) for d in corpus.documents ])
```

Hope that helps
