### ISSUE TITLE
kindred for protein-protein interaction extraction related to species(human, fly, yeast) of interest?

### ISSUE THREAD

**Issue by wasimaftab** [jakelever/kindred#13]
Hi Jake,
Very interesting project. I have gone through the tutorial where you demonstrated annotation. I would like to use kindred to extract protein-protein interaction(PPI) from the literature. For testing purpose I would like to I create a corpus by downloading let's say 10 abstracts from Pubmed.
Since I am new to NLP, therefore, to quickly start working with kindred I have following questions

    1. The names of entities i.e proteins should be in two files as I am looking for a relation between a pair of them? If yes then, do I need to have same list duplicated in two files as I don't know which protein do interact?

    2. Can I use the annotate.py script to start annotating (isInteracting relation) them as you showed in tutorial?

    3. Once I have them annotated how do I create a file listing all extracted protein-protein interactions.

Thanks for your time in advance

**Comment by jakelever** [comment]
As your usecase it slightly different from the tutorial, this would probably be a good time to look inside the Python code for [annotate.py](https://github.com/jakelever/kindred/blob/master/tutorial/annotate.py). Hopefully it's not too horrifying as you would need to make some tweaks for your needs.

1. No, you would only need one file. You would load the wordlist (using loadWordlists), tag the genes/proteins using the EntityRecognizer. Then create all candidate relations (using the CandidateBuilder), you provide acceptedEntityTypes (a parameter) with the option of ('gene','gene') assuming the entity type is 'gene'. This will find all pairs of genes to annotate.

2. The [annotate.py](https://github.com/jakelever/kindred/blob/master/tutorial/annotate.py) script should largely be useful with some slight tweaks.

3. You'd want to look inside the working of the [buildAndUseClassifier.py](https://github.com/jakelever/kindred/blob/master/tutorial/buildAndUseClassifier.py) script in the tutorial. This shows you how to use an annotated set (with relations) to build a classifier, apply it to new sentences and pull out the extracted predicted relations.

**Comment by wasimaftab** [comment]
Hi Jake
Thanks for your  quick reply. I was using pubrunner to download pubmed abstracts
I think I need to change somewhere in the pubrun.py file but can't exactly figure it out. For example, I modified the pubrunner.yml file for TextMiningCounter example as follows. In this example what I care are the 10 abstracts to be downloaded and stored in ~/pubrunner/workspace/TextMiningCounter/test/PUBMED directory. But I see only the last abstract is kept. 

name: TextMiningCounter
version: 0.1
url: https://github.com/jakelever/pubrunner/tree/master/examples/TextMiningCounter
resources:
   full:
      - PUBMED:
         format: txt
      - PMCOA:
         format: txt
   test:
      - PUBMED_CUSTOM:
         pmids:  28893204
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  28117799
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  27317001
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  28755476
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  28430104 
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  27518618
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  24947387
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  27018856
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  18428659
         format: txt
         rename: PUBMED

      - PUBMED_CUSTOM:
         pmids:  16169070
         format: txt
         rename: PUBMED

run:
   - python Count.py --inFile {IN:PUBMED/%} --outFile {OUT:counts/%.txt}
#   - python Count.py --inFile {IN:PMCOA/%} --outFile {OUT:counts/%.txt}
   - python Sum.py --inDir {IN:counts} --outFile {OUT:textminingcount.txt}
output: textminingcount.txt

**Comment by jakelever** [comment]
Instead of multiple PUBMED_CUSTOM blocks, just have one with all the pmids comma-separated, e.g.

```
- PUBMED_CUSTOM:
     pmids:  16169070,18428659,27018856
     format: txt
     rename: PUBMED
```

**Comment by wasimaftab** [comment]
Thanks for your reply. That worked. As per your suggestion I was experimenting with the annotate.py file. I have modified it (https://github.com/wasimaftab/kindred/blob/master/tutorial/annotate.py) and also CandidateBuilder.py (https://github.com/wasimaftab/kindred/blob/master/kindred/CandidateBuilder.py) to accept one wordlists file gene.txt (https://github.com/wasimaftab/kindred/blob/master/tutorial/gene.txt)
I was running following command to annotate protein protein interaction in a set of sentences.
 **python annotate.py --corpus corpus_10.txt --wordlists gene.txt --acceptedEntityTypes 'gene','gene' --outDir ann**
However, i get following error at line 62 in manualAnnotation.py file.
ValueError: not enough values to unpack (expected 2, got 1)

Could you kindly suggest a fix?

Thanks

**Comment by jakelever** [comment]
Hey, looks like you need to change one line:

```
candidateBuilder = kindred.CandidateBuilder(entityCount=len(wordlistDict), acceptedEntityTypes=[tuple(sorted(wordlistDict.keys()))])
```

to

```
candidateBuilder = kindred.CandidateBuilder(entityCount=2,acceptedEntityTypes=[('gene','gene')])
```

For the CandidateBuilder, entityCount is the number of entities in a relation (e.g. 2 for a binary relation) and not the number of genes in your wordlist. Then acceptedEntityTypes is the types of entities in your relation (so you want relations between a gene and a gene).

**Comment by wasimaftab** [comment]
Thanks for your time, the fix worked. However, for real scenario when I have thousands of genes( https://github.com/wasimaftab/kindred/blob/master/tutorial/Gene_Synonyms.txt) mannual annotation will be very time consuming. are there ways to  reduce this manual effort?

**Comment by jakelever** [comment]
Hey, the number of genes doesn't really affect things. You don't need to provide one example for each gene. But you would need to annotate a few hundred sentences to get good performance from Kindred. It's definitely the most time-consuming part of supervised relation extraction.

**Comment by wasimaftab** [comment]
Thanks for your time. Please correct me if I am wrong: First, I use the annotate.py to annotate few hundreds of sentences in which some of my entities (https://github.com/wasimaftab/kindred/blob/master/tutorial/Gene_Synonyms.txt) must present and meanings of these sentences imply entities are interacting, these are positive samples. I also need to  annotate a few hundred sentences more, where my entities are present but those sentences do not imply interaction between them, these are negative samples.  I then use buildAndUseClassifier.py to train a classifier using these data. Finally, I use sentences from pubmed abstracts (not participated in training) to test if I can extract relations accurately. right?

**Comment by jakelever** [comment]
Hi, that's almost correct. The annotate.py script should provide you with positive and negative examples as you will be annotating sentences that are relevant, and some that are not. You would then use this data to build a classifier and evaluate it by splitting your annotated sentences into a training/testing split (e.g. 75%/25%). You could look at the evaluate function for that. That would give you an idea of the expected performance from your classifier. Then you would build a classifier with all your annotated sentences and start applying it to new sentences from PubMed.

**Comment by jakelever** [comment]
Yes, I haven't tried the BioInfer corpus but it should work. Let me know if you run into any issues.

You don't need to provide examples containing every gene/protein in your list, just enough examples of the different types of sentences that they might appear in. From the tutorial, the classifier could deal with new cities/countries if the new sentences look similar to the sentences in the training set.
