### ISSUE TITLE
Questions about CivicMine

### ISSUE THREAD

**Issue by iCHAIT** [jakelever/kindred#17]
Hi Jake,

This is not an issue with the project, rather I have a few questions from your publication [Text-mining clinically relevant cancer biomarkers for curation into the CIViC database](https://www.biorxiv.org/content/biorxiv/early/2018/12/20/500686.full.pdf) that uses this tool. I could not find a better way to reach out to you so I am opening an issue here. Hope you don't mind.

It is a very interesting paper and solves a lot of problem in biomedical text mining. Thanks for the awesome work :)

Here are my Questions - 

1. Referring to the **`Annotation Platform`** Section you discussed in the paper. I want to know if this platform is publicly available and can be used by other people to annotate relationship?

2. Follow up to the above question. Are the **`800 Annotated Sentences`** from the above platform publicly available?

Thank you again for your work. Hope to hear from you soon :)

**Comment by jakelever** [comment]
Hey, glad to hear it's useful.

1. The annotation platform is available [here](https://github.com/jakelever/annotator/tree/master/web). It's a PHP/MySQL application. If you drop that directory into a webserver and access the admin.php page there are controls to import data for annotation. It requires a tar.gz of text annotated with entities in the BioNLP Shared Task format (*.txt with *.a1 files).
2. Sure. The data is available in the [CIViCmine Github repo](https://github.com/jakelever/civicmine/) in the [data/](https://github.com/jakelever/civicmine/tree/master/data) directory

**Comment by iCHAIT** [comment]
Thanks for the clarification :)
