### ISSUE TITLE
Passage OffSets or Document Offsets?

### ISSUE THREAD

**Issue by ozborn** [jakelever/kindred#18]
I am trying to parse the 2015 Biocreative Corpus which is in BIOC format using kindred as shown below:

```
    corpus = kindred.loadFunctions.load("biocxml",args.dirNorm)
```
However, the corpus uses the "Passage" annotation (used for Title, Abstract, etc..) and has a different passage for calculates offsets from the start of the document rather than immediate passage. So for example, to get the correct offset for annotation #3 "tricuspid regurgitation" it would require a calculation of 105 (its offset) - 82 (offset of preceding passage). Right now only the 1st passage is handled by kindred.

I couldn't find the specification details to see if kindred should be doing this differently, or if the Biocreativ folks didn't follow the BIOC specification correctly. In the first case, maybe kindred could fix this issue. In the 2nd case, I could just write my own parser to pull what I need from the corpus. An example from the beginning of the file is shown below. 

Thanks for any help.

```
<?xml version='1.0' encoding='UTF-8'?><!DOCTYPE collection SYSTEM 'BioC.dtd'>
<collection>
<source>PubTator</source>
<date>0/0/0</date>
<key>PubTator.key</key>
<document>
<id>6794356</id>
<passage>
<infon key="type">title</infon>
<offset>0</offset>
<text>Tricuspid valve regurgitation and lithium carbonate toxicity in a newborn infant.</text>
<annotation id='0'>
<infon key="type">Disease</infon>
<infon key="MESH">D014262</infon>
<location offset='0' length='29' />
<text>Tricuspid valve regurgitation</text>
</annotation>
<annotation id='1'>
<infon key="type">Chemical</infon>
<infon key="MESH">D016651</infon>
<location offset='34' length='17' />
<text>lithium carbonate</text>
</annotation>
<annotation id='2'>
<infon key="type">Disease</infon>
<infon key="MESH">D064420</infon>
<location offset='52' length='8' />
<text>toxicity</text>
</annotation>
</passage>
<passage>
<infon key="type">abstract</infon>
<offset>82</offset>
<text>A newborn with massive tricuspid regurgitation, atrial flutter, congestive heart failure, and a high serum lithium level is described. This is the first patient to initially manifest tricuspid regurgitation and atrial flutter, and the 11th described patient with cardiac disease among infants exposed to lithium compounds in the first trimester of pregnancy. Sixty-three percent of these infants had tricuspid valve involvement. Lithium carbonate may be a factor in the increasing incidence of congenital heart disease when taken during early pregnancy. It also causes neurologic depression, cyanosis, and cardiac arrhythmia when consumed prior to delivery.</text>
<annotation id='3'>
<infon key="type">Disease</infon>
<infon key="MESH">D014262</infon>
<location offset='105' length='23' />
<text>tricuspid regurgitation</text>
</annotation>
```

**Comment by jakelever** [comment]
Hi, thanks for raising this issue. I'm travelling at the moment and will get into this when I get back next week.

**Comment by ozborn** [comment]
Thanks Jake!

**Comment by jakelever** [comment]
Hi, I've made a fix to the loading code so that passage offsets are loaded correctly. Thanks for raising this. I've pushed out a new version with this fix to pip.

I just tried loading the [Biocreative V CDR corpus](https://biocreative.bioinformatics.udel.edu/tasks/biocreative-v/track-3-cdr/), which is what I'm assuming you're loading. I've found a few annotation errors in the data which would require a little adjusting. The offsets are incorrect for a single annotation in the development set and for two annotations in the testing set.

For example, at roughly line 9919 of CDR_DevelopmentSet.BioC.xml. The annotation (shown below) aligns with two spans " atypical absenc" and "seizures" in the text.  See the first location is wrong and should have an offset of 246 instead of 247. This needs manual fixing. There are a couple more in the testing set.

```xml
<annotation id="8">
	<infon key="type">Disease</infon>
	<infon key="CompositeRole">IndividualMention</infon>
	<infon key="MESH">D004832</infon>
	<location offset="247" length="16"/>
	<location offset="293" length="8"/>
	<text>atypical absence seizures</text>
</annotation>
```

**Comment by ozborn** [comment]
Thanks Jake! Yes, I am loading the Biocreative V CDR Corpus - appreciate the warnings about annotation errors. Will take a look and get back to you.

**Comment by jakelever** [comment]
Great!

**Comment by ozborn** [comment]
Just wanted to let you know it works great for me, thanks!

**Comment by jakelever** [comment]
Great. Thanks for letting me know
