### ISSUE TITLE
is there exists a annotation tool handling more entites relations

### ISSUE THREAD

**Issue by zengxianhua** [jakelever/kindred#19]
hi, in the tutorial , you gives an annotation tool handling two entity relations, is there exists a annotation tool handling more entites relations?

**Comment by jakelever** [comment]
Hey, I've been working with the [TextAE annotator](http://textae.pubannotation.org/) recently, or else there was a nice review of annotation tools recently that might cover what you're looking for. Hope that helps.

[Neves, Mariana, and Jurica Ševa. "An extensive review of tools for manual annotation of documents." Briefings in Bioinformatics (2019).](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbz130/5670958)

**Comment by zengxianhua** [comment]
Thanks for your responding. Does kindred only support exact string matching in NER(named entity recognition) ? I cannot find methods supporting fuzzy matching, ever some synonyms or pluras pattern of some words in the dict cannot be recoginized.

**Comment by jakelever** [comment]
Unfortunately Kindred only supports exact matching at the moment.
