### ISSUE TITLE
ValueError on classifier.train() line

### ISSUE THREAD

**Issue by ozmosi-pharma** [jakelever/kindred#20]
Hello,
I am using Anaconda environment (running as an administrator) with Jupyter, python 3.7, spacy 2.0.1 and I get the following error 
ValueError: spacy.syntax.nn_parser.Parser size changed, may indicate binary incompatibility. Expected 72 from C header, got 64 from PyObject

on line classifier.train(trainCorpus). Do you have any suggestions to fix this ?

**Comment by jakelever** [comment]
Hmm, this sounds like a spacy error. Have you tried updating to the latest version of spacy?
