### ISSUE TITLE
Saving trained classifier

### ISSUE THREAD

**Issue by manjumbmb97** [jakelever/kindred#21]
I've trained the RelationClassifier() on a corpus and want to save and re-use it in future as it'll be annoying to train it every time. 
But I couldn't find an option to save it.
It'll be very helpful, if anyone suggests a way to save trained RelationClassifier().

**Comment by jakelever** [comment]
Great. You should be able to pickle it to save it, e.g.

```python
import pickle

classifier = RelationClassifier()
classifier.train(corpus)

with open('classifier.pickle','wb') as f:
    pickle.dump(classifier,f)
```

**Comment by manjumbmb97** [comment]
Thank you. It works :)
