### ISSUE TITLE
Evaluate returns zero

### ISSUE THREAD

**Issue by seesiva** [jakelever/kindred#22]
When  tried to call on the tutorial example with evaluate method it returns 0.0. Any suggestions?

**Comment by jakelever** [comment]
Hey, can you post the code you're using for the evaluation?

Also, I just did a small update so it might be worth trying to again (after updating kindred).

**Comment by seesiva** [comment]
I was running the code from tutorial.

Please find the current Kindred version
![image](https://user-images.githubusercontent.com/3206488/110403359-fc3f5b80-80a2-11eb-9eba-8d49b915e16e.png)

Code I'm using for evaluate
`results = kindred.evaluate(trainCorpus, predictionCorpus, metric='all', display=True)
`
Result upon execution
![image](https://user-images.githubusercontent.com/3206488/110403183-ac609480-80a2-11eb-85fe-b04a697e3315.png)

**Comment by jakelever** [comment]
Thanks for the extra details. Very helpful.

It looks like you're comparing the corpus used to train the classifier with the corpus that contains new predictions. These will contain different sentences so it would be expected that you'd get zero for performance.

What you would need to do is make predictions on a corpus where you have annotations. The shared task example does this:

```
import kindred
trainCorpus = kindred.bionlpst.load('2016-BB3-event-train')
devCorpus = kindred.bionlpst.load('2016-BB3-event-dev')
predictionCorpus = devCorpus.clone()
predictionCorpus.removeRelations()
classifier = kindred.RelationClassifier()
classifier.train(trainCorpus)
classifier.predict(predictionCorpus)
f1score = kindred.evaluate(devCorpus, predictionCorpus, metric='f1score')
```

With your own data, you could split up a corpus into trainCorpus and devCorpus:

```
myCorpus = # loading or creating it
trainCorpus, devCorpus = myCorpus.split(0.75)
```
