### ISSUE TITLE
Detailed explanation for the different file formats

### ISSUE THREAD

**Issue by jakelever** [jakelever/kindred#3]
The docs need a page that specifically describes the different file formats. With answers for questions like:
- Does the standoff format need IDs that starts with T and R? What about E or others?
  - Answer: Yes. T must be used for entities and R must be used for relations (I think)
- Does the Simple Tag format have to have subj and obj arguments in the relation?
  - Answer: No. Any attributes excluding "id" and "type" are assumed to be arguments for the relation. The values of those attributes must match with names of entities within the same data

**Comment by chenwi** [comment]
when I use this code，classifier.train(trainCorpus)，it run error.
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by jakelever** [comment]
@chenwi It sounds like you need to install the English language model for Spacy (the underlying dependency parser). The command is below:

```
python -m spacy download en
```
